defaultProject: max-ostapenko
defaultLocation: US
defaultDataset: all
defaultAssertionDataset: dataform_assertions

vars:
    test_var: test
    # current_month: 2024-07-01 # must be commented in main branch, only for manual executions