config {
    type: "operations",
    hasOutput: true,
    disabled: true  // MUST NOT be commented in main branch
}

CREATE OR REPLACE TABLE ${ref("all", "pages")} AS
SELECT *
FROM `httparchive.all.pages` ${constants.dev_TABLESAMPLE}
WHERE date = '${constants.past_month}';

CREATE OR REPLACE TABLE ${ref("all", "requests")} AS
SELECT *
FROM `httparchive.all.requests` ${constants.dev_TABLESAMPLE}
WHERE date = '${constants.past_month}';

CREATE OR REPLACE TABLE ${ref("all", "parsed_css")} AS
SELECT *
FROM `httparchive.all.parsed_css` ${constants.dev_TABLESAMPLE}
WHERE date = '${constants.past_month}';

CREATE OR REPLACE TABLE ${ref("core_web_vitals", "technologies")} AS
SELECT *
FROM `httparchive.core_web_vitals.technologies`
WHERE date = '${constants.past_month}'