config {
    type: "incremental",
}

INSERT INTO
  `all.pages`
SELECT
  *
FROM
  `test.pages`
WHERE
  date = '${constants.date}'
  AND client = 'desktop'
  AND is_root_page;

INSERT INTO
  `all.pages`
SELECT
  *
FROM
  `test.pages`
WHERE
  date = '${constants.date}'
  AND client = 'desktop'
  AND is_root_page = FALSE

pre_operations {
  DELETE
  FROM
    ${self()}
  WHERE
    date = '${constants.date}';
}