// SPDX-FileCopyrightText: 2026 Google LLC
// SPDX-License-Identifier: Apache-2.0

// Regenerates `includes/public_suffix_private.js` from the PRIVATE DOMAINS
// section of the Public Suffix List. BigQuery's `NET.PUBLIC_SUFFIX()` and
// `NET.REG_DOMAIN()` only apply the ICANN section, so hosts like
// `alice.github.io` and `bob.github.io` would otherwise collapse into the
// single site `github.io`.
//
// Usage: node scripts/update_public_suffix_private.mjs

import { writeFile } from 'node:fs/promises'
import { domainToASCII } from 'node:url'

const PSL_URL = 'https://publicsuffix.org/list/public_suffix_list.dat'
const OUTPUT = new URL('../includes/public_suffix_private.js', import.meta.url)

const response = await fetch(PSL_URL)
if (!response.ok) {
  throw new Error(`Fetching ${PSL_URL} failed: ${response.status}`)
}
const text = await response.text()

const begin = text.indexOf('// ===BEGIN PRIVATE DOMAINS===')
const end = text.indexOf('// ===END PRIVATE DOMAINS===')
if (begin === -1 || end === -1) {
  throw new Error('PRIVATE DOMAINS section not found')
}

const exact = new Set()
const wildcard = new Set()
for (const rawLine of text.slice(begin, end).split('\n')) {
  const line = rawLine.trim()
  if (!line || line.startsWith('//')) continue
  // The PSL format allows exception rules (`!`), but the private section has
  // none today. Fail loudly so the SQL gets extended if that ever changes.
  if (line.startsWith('!')) {
    throw new Error(`Exception rules are not supported: ${line}`)
  }
  const isWildcard = line.startsWith('*.')
  // Crawled hosts are punycode, so match them against punycode rules.
  const rule = domainToASCII(isWildcard ? line.slice(2) : line)
  if (!rule) throw new Error(`Invalid rule: ${line}`)
  ;(isWildcard ? wildcard : exact).add(rule)
}

const list = (values) =>
  [...values]
    .sort()
    .map((value) => `  '${value}'`)
    .join(',\n')

await writeFile(
  OUTPUT,
  `// SPDX-FileCopyrightText: 2026 Google LLC
// SPDX-License-Identifier: Apache-2.0

// Generated by scripts/update_public_suffix_private.mjs from
// ${PSL_URL}. Do not edit by hand.

// Rules like \`github.io\`: the suffix itself is public.
const exact = [
${list(exact)}
]

// Rules like \`*.compute.amazonaws.com\`, stored without the leading \`*.\`:
// every direct child of the suffix is public.
const wildcard = [
${list(wildcard)}
]

module.exports = {
  exact,
  wildcard
}
`
)

console.log(`${exact.size} exact and ${wildcard.size} wildcard rules written`)
