name: Deploy to cloud
on:
  push:
    branches:
      - main
    paths:
      - infra/**

permissions: {}

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v1

      - name: Run Terraform apply
        run: make tf_apply
