name: Deploy to cloud
on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: google_auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v1

      - name: Determine files changed
        id: diff_check
        run: |
          files_changed=$(git diff --name-only HEAD^ HEAD)
          echo "files_changed=$files_changed" >> $GITHUB_ENV

      - name: 'Run Terraform apply if tf changes detected'
        if: contains(env.files_changed, 'infra/tf/')
        run: make tf_apply

      - name: 'Run deploy function if trigger_function changes detected'
        if: contains(env.files_changed, 'infra/trigger_function/')
        run: make deploy_fn
