name: Linter

on:
  workflow_dispatch:
  pull_request: null
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      statuses: write # To report GitHub Actions status checks

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v7.1.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSCPD: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_GITHUB_ACTIONS: false
